<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{PAGE_TITLE}}</title>
    <style>
      @keyframes f {
        from {
          opacity: 0;
          transform: translateY(10px);
        }
        to {
          opacity: 1;
          transform: translateY(0);
        }
      }
      body {
        background-image: url("https://images.unsplash.com/photo-1550684376-efcbd6e3f031?q=80&w=2070&auto=format&fit=crop");
        background-size: cover;
        background-position: center;
        background-attachment: fixed;
        color: #e0e0e0;
        font-family: "Segoe UI", Roboto, sans-serif;
        padding: 2em;
        line-height: 1.6;
        -webkit-print-color-adjust: exact !important;
        color-adjust: exact !important;
      }
      .container {
        max-width: 1200px;
        margin: 0 auto;
      }
      header {
        text-align: center;
        padding: 1rem 0;
      }
      header h1 {
        color: #fff;
        font-weight: 600;
        text-shadow: 0 0 15px rgba(0, 255, 157, 0.5);
      }
      header .summary {
        color: #ccc;
        font-size: 1.1em;
      }
      .excluded-box {
        background: rgba(255, 100, 100, 0.1);
        border: 1px solid rgba(255, 100, 100, 0.2);
        border-radius: 8px;
        padding: 10px;
        margin-top: 15px;
        font-size: 0.9em;
      }
      .excluded-box strong {
        color: #ffcccc;
      }
      .output-box {
        background: rgba(40, 40, 40, 0.65);
        backdrop-filter: blur(12px);
        -webkit-backdrop-filter: blur(12px);
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 12px;
        padding: 1.5em;
        box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
        font-family: "Fira Code", "Courier New", monospace;
        margin-top: 2rem;
      }
      .line {
        display: flex;
        align-items: center;
        padding: 10px 15px;
        border-bottom: 1px solid rgba(255, 255, 255, 0.08);
        white-space: nowrap;
        overflow: hidden;
        gap: 1em;
        animation: f 0.5s ease-out forwards;
      }
      .line:last-child {
        border-bottom: none;
      }
      .url {
        flex: 0 1 40%;
        color: #61dafb;
        text-overflow: ellipsis;
        overflow: hidden;
      }
      .status {
        flex: 0 0 15%;
        display: flex;
        align-items: center;
        gap: 8px;
      }
      .info {
        flex: 1 1 45%;
        color: #ffcc00;
        text-overflow: ellipsis;
        overflow: hidden;
      }
      a {
        color: inherit;
        text-decoration: none;
      }
      footer {
        text-align: center;
        padding-top: 2rem;
        color: #aaa;
        font-size: 0.9em;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <header>
        <h1>{{PAGE_TITLE}}</h1>
        <p class="summary">
          Total Live Subdomains Found: <strong>{{LIVE_DOMAINS}}</strong>
        </p>
        {{EXCLUDED_SECTION}}
      </header>
      <main class="output-box">
        {{DOMAIN_ROWS}}
      </main>
      <footer>
        <p>Generated by Subwhisper on {{DATE}}</p>
      </footer>
    </div>
  </body>
</html>
